
# Markets you wish to collect data for
MARKETS = [
    'BTCUSDT', 'ETHUSDT', '1000SHIBUSDT',
    'GMTUSDT', 'MTLUSDT', 'SOLUSDT',
    'NEARUSDT', 'LUNAUSDT', 'APEUSDT',
    'ETCUSDT', 'XRPUSDT', 'DOTUSDT',
    'FTMUSDT', 'AXSUSDT', 'KNCUSDT',
    'GALAUSDT', 'BCHUSDT', 'CHZUSDT',
    'LTCUSDT', 'MATICUSDT', 'SANDUSDT',
    'ATOMUSDT', 'XMRUSDT', 'LINKUSDT',
    'C98USDT', 'EOSUSDT', 'FILUSDT',
    'AAVEUSDT', 'MANAUSDT', 'ANKRUSDT',
    'LRCUSDT', 'VETUSDT', 'THETAUSDT',
    'IOSTUSDT', 'SRMUSDT', 'PEOPLEUSDT',
    'ALICEUSDT', 'ZECUSDT', 'COMPUSDT',
    'STORJUSDT', 'DYDXUSDT', 'ALGOUSDT',
    'SNXUSDT', 'OGNUSDT', 'ICPUSDT',
    'ALPHAUSDT', 'CRVUSDT', 'ENJUSDT',
    'ONEUSDT', 'CELOUSDT', 'SUSHIUSDT',
    'ROSEUSDT', 'KAVAUSDT', 'SKLUSDT',
    'UNIUSDT', 'EGLDUSDT', 'AUDIOUSDT',
    'COTIUSDT', 'CVCUSDT', 'KSMUSDT',
    'TRXUSDT', 'XTZUSDT', 'CELRUSDT',
    'GRTUSDT', 'HOTUSDT', 'BALUSDT',
    'DUSKUSDT', 'TLMUSDT', 'CHRUSDT',
    'BNXUSDT', 'IMXUSDT', 'XLMUSDT',
    'REEFUSDT', 'DASHUSDT', 'DODOUSDT',
    'HNTUSDT', 'ARUSDT', '1INCHUSDT',
    'BAKEUSDT', 'ZRXUSDT', 'ANCUSDT',
    'RLCUSDT', 'FLOWUSDT', 'OMGUSDT',
    'ICXUSDT', 'QTUMUSDT', 'IOTAUSDT',
    'SXPUSDT', 'RSRUSDT', 'LITUSDT',
    'NEOUSDT', 'WOOUSDT', 'LINAUSDT',
    'TOMOUSDT', 'HBARUSDT', 'BANDUSDT',
    'YFIUSDT', 'CTXUSDT', 'ENSUSDT',
    'ZENUSDT', 'ATAUSDT', 'BLZUSDT',
    'API3USDT', 'BATUSDT', 'GTCUSDT',
    'MASKUSDT', 'ONTUSDT', 'ARPAUSDT',
    'MKRUSDT', 'RAYUSDT', 'IOTXUSDT',
]

# Time interval
INTERVAL = '15m'

# Start time
START_TIME = 1609462861
